apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: esp32
  namespace: akri
spec:
  discoveryHandler:
    name: udev
    discoveryDetails: |+
      udevRules:
        - 'SUBSYSTEM=="tty", KERNEL=="ttyUSB*", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60"'
      permissions: rwm
      groupRecursive: false
  capacity: 1
