apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-harbor-tls
spec:
  commonName: harbor.sigurs.io
  secretName: external-harbor-tls
  dnsNames: 
    - harbor.sigurs.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-harbor
subsets:
  - addresses:
      - ip: 172.20.4.10
    ports:
      - port: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: external-harbor
spec:
  clusterIP: None
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-harbor
spec:
  tls:
    - hosts:
        - harbor.sigurs.io
      secretName: external-harbor-tls
  rules:
    - host: harbor.sigurs.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: external-harbor
              port:
                number: 8081