apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# serving-crds actually not needed, only causes issues: https://github.com/knative/serving/issues/12032
#  - https://github.com/knative/serving/releases/download/knative-v1.18.0/serving-crds.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.18.0/serving-core.yaml