node-ip: {{ private_ip }}
node-external-ip: {{ ansible_host }}

{% if k3s.node_labels is defined -%}
node-label:
{% for label in k3s.node_labels %}
  - {{label}}
{% endfor %}
{% endif %}

# For cilium
#flannel-backend: "none"

# Harden the cluster
protect-kernel-defaults: true
kubelet-arg:
  - "feature-gates=UserNamespacesSupport=true,UserNamespacesPodSecurityStandards=true"
  - 'streaming-connection-idle-timeout=5m'
  - "tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
  - "cloud-provider=external"  # Needed for hcloud-ccm
kube-proxy-arg:
  - "feature-gates=UserNamespacesSupport=true,UserNamespacesPodSecurityStandards=true"
