apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-jellyfin-tls
spec:
  commonName: jellyfin.sigurs.io
  secretName: external-jellyfin-tls
  dnsNames: 
    - jellyfin.sigurs.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-jellyfin
subsets:
  - addresses:
      - ip: 172.20.4.10
    ports:
      - port: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: external-jellyfin
spec:
  clusterIP: None
  ports:
    - port: 8096
      targetPort: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-jellyfin
spec:
  tls:
    - hosts:
        - jellyfin.sigurs.io
      secretName: external-jellyfin-tls
  rules:
    - host: jellyfin.sigurs.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: external-jellyfin
              port:
                number: 8096