apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-paperless-tls
spec:
  commonName: paperless.sigurs.io
  secretName: external-paperless-tls
  dnsNames: 
    - paperless.sigurs.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-paperless
subsets:
  - addresses:
      - ip: 172.20.4.10
    ports:
      - port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: external-paperless
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-paperless
spec:
  tls:
    - hosts:
        - paperless.sigurs.io
      secretName: external-paperless-tls
  rules:
    - host: paperless.sigurs.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: external-paperless
              port:
                number: 8000