apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  project: home-k8s.admin
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: v35.2.0
      helm:
        valuesObject:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
    - repoURL: https://github.com/Sigurs/gitops.git
      targetRevision: HEAD
      path: home-k8s/admin-traefik/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik