apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: shared-postgres
spec:
  instances: 1
  storage:
    size: 1Gi

  managed:
    roles:
      - name: shared-keycloak
        ensure: present
        login: true

