apiVersion: v1
kind: Namespace
metadata:
  name: shared-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: shared-services