apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundryvtt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: foundryvtt
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foundryvtt
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
      containers:
      - name: foundryvtt
        image: registry.sigurs.io/sigurs/foundryvtt:12.331
        ports:
          - containerPort: 30000
            name: http
        volumeMounts:
          - mountPath: "/data"
            name: foundryvtt
      volumes:
        - name: foundryvtt
          persistentVolumeClaim:
            claimName: foundryvtt
