apiVersion: apps/v1
kind: Deployment
metadata:
  name: 5etools
spec:
  selector:
    matchLabels:
      app: 5etools
  replicas: 1 # You could also consider elastic scaling for this deployment
  template:
    metadata:
      labels:
        app: 5etools
    spec:
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: 5etools
        image: ghcr.io/5etools-mirror-2/5etools:1.207.2
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
