apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-traefik
  namespace: infra-argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 28.3.0
    helm:
      valuesObject:
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
      traefik:
        ports:
          web:
            nodePort: 80
          websecure:
            nodePort: 443
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
