apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-traefik
  namespace: infra-argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 28.3.0
    helm:
      releaseName: traefik
      valuesObject:
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        podSecurityContext:
          seccompProfile:
            type: RuntimeDefault
#        ports:
#          web:
#            nodePort: 30080
#          websecure:
#            nodePort: 30443
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-traefik
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
