apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-hcloud-ccm
  namespace: infra-argocd
spec:
  project: default
  source:
    chart: hccm
    repoURL: https://charts.hetzner.cloud
    targetRevision: 1.19.0
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-hcloud-ccm
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
