apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-traefik
spec:
  project: default
  source:
    chart: traefik
    repoURL: traefik.github.io/charts
    targetRevision: latest
  destination:
    name: in-cluster
    namespace: infra-traefik
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
