apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-hcloud-ccm
  namespace: infra-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sigurs/gitops.git
    targetRevision: HEAD
    path: hcloud-cluster01/infra-hcloud-ccm/base
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-hcloud-ccm
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
