apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-whoami
  namespace: infra-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sigurs/gitops.git
    targetRevision: HEAD
    path: hcloud-cluster01/whoami
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-whoami
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
