apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: home-k8s
  source:
    chart: traefik
    repoURL: https://charts.jetstack.io
    targetRevision: 1.17.2
    helm:
      releaseName: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager