apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      automountServiceAccountToken: false
      containers:
      - name: whoami
        image: traefik/whoami:latest
        ports:
          - containerPort: 80
            name: http
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
