apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: change-detection
spec:
  project: home-k8s
  source:
    repoURL: https://github.com/Sigurs/gitops.git
    targetRevision: HEAD
    path: home-k8s/apps/change-detection
  destination:
    server: https://kubernetes.default.svc
    namespace: change-detection
  syncPolicy:
    syncOptions:
      - ServerSideApply=true