apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
spec:
  tls:
  - hosts:
      - KUSTOMIZE_PATCH
    secretName: hass-tls
  rules:
  - host: KUSTOMIZE_PATCH
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hass
            port:
              name: http
