apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
spec:
  rules:
  - host: hass.sigurs.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hass
            port:
              name: http
