apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: proxima-apps
  namespace: infra-argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - git@github.com:Sigurs/gitops-private.git
  - https://github.com/Sigurs/gitops.git
  