- name: apply common
  become: yes
  hosts: 
    - all
  roles:
    - 00-common

- name: apply k3s-bootstrap
  become: yes
  hosts:
    - k3s_servers[0]
  roles:
    - 01-k3s-bootstrap
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: apply k3s-agent
  become: yes
  hosts:
    - k3s_agents
  roles:
    - 03-k3s-agent
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: apply gitops-bootstrap
  become: yes
  hosts:
    - k3s_servers[0]
  roles:
    - 04-gitops-bootstrap
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml