apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
spec:
  rules:
    - host: chat.home-k8s.sigurs.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: open-webui
              port:
                name: http