apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-cloudflared
spec:
  selector:
    matchLabels:
      app: infra-cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: infra-cloudflared
    spec:
      automountServiceAccountToken: false
      hostUsers: false
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2025.9.1
        env:
          - name: TUNNEL_METRICS
            value: "0.0.0.0:2000"
          - name: NO_AUTOUPDATE
            value: "true"
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: infra-cloudflared
                key: TUNNEL_TOKEN
        args:
        - tunnel
        - run
        livenessProbe:
          httpGet:
            # Cloudflared has a /ready endpoint which returns 200 if and only if
            # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
