apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: system-upgrade-server-plan
  annotations:
    # Make sure controller is deployed before plans
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.34.1+k3s1