apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  annotations:
    # Make sure controller is deployed before plans
    argocd.argoproj.io/sync-wave: "1"
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/control-plane
      operator: In
      values:
      - "true"
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  # Enable automatic upgrades
  channel: https://update.k3s.io/v1-release/channels/stable