apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-traefik-cloudflared
  namespace: infra-argocd
spec:
  project: proxima-infra
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: v37.1.1
      helm:
        valuesObject:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-traefik-cloudflared
  syncPolicy:
    syncOptions:
      - ServerSideApply=true