apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-argocd
spec:
  project: proxima-infra
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: v8.5.7
      helm:
        valueFiles:
          - $gitops-public/proxima/infra/argocd/values.yaml
    - repoURL: 'https://github.com/Sigurs/gitops.git'
      targetRevision: HEAD
      ref: gitops-public
    - repoURL: https://github.com/Sigurs/gitops.git
      targetRevision: HEAD
      path: proxima/infra/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-argocd  
  # syncPolicy:
  #   automated:
  #     enabled: true