apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-keycloak
spec:
  project: proxima-apps
  source:
    repoURL: https://github.com/Sigurs/gitops.git
    targetRevision: HEAD
    path: proxima/shared/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: shared-keycloak
  syncPolicy:
    syncOptions:
      - ServerSideApply=true