apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: proxima.apps
  namespace: argocd
spec:
  clusterResourceWhitelist: []
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - https://github.com/Sigurs/gitops.git