apiVersion: apps/v1
kind: Deployment
metadata:
  name: hass
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hass
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hass
    spec:
      automountServiceAccountToken: false
      hostUsers: false
      containers:
      - name: hass
        image: ghcr.io/home-assistant/home-assistant:stable
        securityContext:
          # Requires root inside the container to run.
          # We are using UserNamespaces to mitigate security issues. 
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
        env:
          - name: TZ
            value: Europe/Helsinki
          - name: DISABLE_JEMALLOC
            value: "true"
        ports:
          - containerPort: 8123
            name: http
        volumeMounts:
          - name: hass
            mountPath: /config
            subPath: config
      volumes:
        - name: hass
          persistentVolumeClaim:
            claimName: hass