apiVersion: v1
kind: Service
metadata:
  name: hass
spec:
  selector:
    app.kubernetes.io/name: hass
  ports:
  - name: http
    protocol: TCP
    port: 8123
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: hass-meshtastic
spec:
  selector:
    app.kubernetes.io/name: hass
  ports:
    - port: 4403
      targetPort: 4403
  type: LoadBalancer