apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: infra-hcloud
spec:
  endpointSelector: {}
  ingress:
    - {}
  egress:
    # DNS access
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"

    # Kubernetes API access
    - toServices:
        - k8sService:
            serviceName: kubernetes
            namespace: default
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

    # Hetzner API access
    - toFQDNs:
        - matchPattern: "api.hetzner.cloud"