apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - netpol.yaml
#  - nfs-test.yaml

patches:
  - path: deployment-patch.yaml
  - path: tls-patch.yaml
  - path: ingress-patch.yaml