---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hass-unraid-models
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: hass-unraid-models
  storageClassName: nfs-unraid
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  name: hass-unraid-models
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-unraid
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: unraid.sigurs.io/share##
    volumeAttributes:
      server: unraid.sigurs.io/
      share: mnt/user/models