apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.0.5/manifests/install.yaml
  - ingress.yaml
#  - tls.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd
    target:
      kind: ClusterRoleBinding
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-cm-patch.yaml
