apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps.private
spec:
  sourceRepos:
    - ssh://git@github.com/Sigurs/gitops-private.git
  sourceNamespaces: []
  destinations: 
    - server: https://kubernetes.default.svc
      namespace: ''
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: '*'
    - group: ''
      kind: PersistentVolumeClaim