apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard
    spec:
      automountServiceAccountToken: false
      hostUsers: false
      containers:
      - name: adguard
        image: adguard/adguardhome:latest
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        ports:
          - containerPort: 53
            name: dns
          - containerPort: 80
            name: http
          - containerPort: 443
            name: dns-over-https
          - containerPort: 3000
            name: http-webui
          - containerPort: 853
            name: dns-over-tls
          - containerPort: 5443
            name: dnscrypt

        volumeMounts:
          - name: adguard
            mountPath: /opt/adguardhome/work
            subPath: opt/adguardhome/work
          - name: adguard
            mountPath: /opt/adguardhome/conf
            subPath: opt/adguardhome/conf
      volumes:
        - name: adguard
          persistentVolumeClaim:
            claimName: adguard