apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard
spec:
  tls:
  - hosts:
      - KUSTOMIZE_PATCH
    secretName: adguard-tls
  rules:
  - host: KUSTOMIZE_PATCH
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adguard-http
            port:
              name: http-webui
