apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-tls
spec:
  commonName: KUSTOMIZE_PATCH
  secretName: adguard-tls
  dnsNames: 
    - KUSTOMIZE_PATCH
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt