apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
spec:
  commonName: argocd.home-k8s.sigurs.io
  secretName: argocd-tls
  dnsNames: 
    - argocd.home-k8s.sigurs.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt