apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-tls
spec:
  commonName: argocd.home-k8s.sigurs.io
  secretName: adguard-tls
  dnsNames: 
    - argocd.home-k8s.sigurs.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging