apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-keycloak-proxy
data:
  default.conf: |
    server {
        listen       8080;
        server_name  localhost;

        location / {
            proxy_pass http://shared-keycloak.shared-keycloak.svc:8080;
        }

        location ^~ /admin/ {
            deny all;
            return 403;
        }
    }