apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: home-k8s.admin
  source:
    repoURL: https://github.com/Sigurs/gitops.git
    targetRevision: HEAD
    path: home-k8s/admin/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true