apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-smb
spec:
  project: home-k8s.admin
  sources:
    - chart: csi-driver-smb
      repoURL: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
      targetRevision: 1.17.0
    - repoURL: https://github.com/Sigurs/gitops.git
      targetRevision: HEAD
      path: home-k8s/admin/csi-driver-smb/overlays/home-k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-driver-smb