apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-istiod
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: home-k8s.admin
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.26.1
    helm:
      valuesObject:
        defaultRevision: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system