apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: home-k8s.admin
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.26.1
    helm:
      valuesObject:
        # Disable istio-ingress service 
        service:
          type: None

        defaultRevision: default
        securityContext:
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: 
              - ALL
          
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress