apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: home-k8s.admin
  source:
    chart: istio/gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.26.1
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress