apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackrox-central-services
spec:
  project: home-k8s.admin
  source:
    chart: stackrox-central-services
    repoURL: https://raw.githubusercontent.com/stackrox/helm-charts/main/opensource/
    helm:
      valuesObject:
        # Generate CA
        ca:
          generate: true 
        # Disabled already deprecated PodSecurityPolicies
        system:
          enablePodSecurityPolicies: false
        central:
          # Generate admin password
          adminPassword:
            generate: true
          persistence:
            none:  true
          resources:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 4Gi
              cpu: 1
          db:
            resources:
              requests:
                memory: 128Mi
                cpu: 10m
              limits:
                memory: 4Gi
                cpu: 1
        scanner:
          disable: true
          autoscaling:
            disabled: true
          replicas: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 10m
            limits:
              memory: 4Gi
              cpu: 1

        scannerV4: 
          disabled: false
          db:
            # Auto-generate and trust the certs
            serviceTLS:
              generate: true 
            resources:
              requests:
                memory: 128Mi
                cpu: 10m
              limits:
                memory: 4Gi
                cpu: 1
          indexer:
            replicas: 1
            autoscaling:
              disable: true
            # Auto-generate and trust the certs
            serviceTLS:
              generate: true 
            resources:
              requests:
                memory: 128Mi
                cpu: 10m
              limits:
                memory: 4Gi
                cpu: 1
          matcher:
            replicas: 1
            autoscaling:
              disable: true
            # Auto-generate and trust the certs
            serviceTLS:
              generate: true 
            resources:
              requests:
                memory: 128Mi
                cpu: 10m
              limits:
                memory: 4Gi
                cpu: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: stackrox