apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-access-to-unraid
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        # host: unraid
        - ipBlock:
            cidr: 172.20.4.10/32