apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin/argocd.yaml
  - admin/cert-manager.yaml
  - admin/system-upgrade-controller.yaml
  - admin/traefik.yaml
  
  - apps/prod-adguard.yaml
  - apps/prod-hass.yaml