apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-files-appdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hcloud-volumes