apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
spec:
  commonName: KUSTOMIZE_PATCH
  secretName: wildcard-tls
  dnsNames: 
    - KUSTOMIZE_PATCH
  issuerRef:
    kind: ClusterIssuer
    name: KUSTOMIZE_PATCH