apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: change-detection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path-retain