- name: enable and restart k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: enable and restart snapd
  ansible.builtin.systemd:
    name: snapd
    state: restarted
    enabled: yes
    daemon_reload: yes